/* eslint-disable @typescript-eslint/naming-convention */
import type { EslintRules } from "eslint-define-config";

export default {
    "accessor-pairs": "error",
    "array-bracket-newline": ["error", { multiline: true }],
    "array-bracket-spacing": "error",
    "array-callback-return": ["error", { checkForEach: true }],
    "array-element-newline": ["error", "consistent"],
    "arrow-body-style": "error",
    "arrow-parens": "error",
    "arrow-spacing": "error",
    "block-scoped-var": "error",
    "block-spacing": "error",
    "brace-style": "error",
    "callback-return": "off",
    camelcase: "error",
    "capitalized-comments": ["error", "always", { ignoreInlineComments: true }],
    "class-methods-use-this": "error",
    "comma-dangle": ["error", "always-multiline"],
    "comma-spacing": "error",
    "comma-style": "error",
    complexity: ["error", 50],
    "computed-property-spacing": "error",
    "consistent-return": ["error", { treatUndefinedAsUnspecified: true }],
    "consistent-this": "error",
    "constructor-super": "error",
    curly: ["error", "multi-or-nest", "consistent"],
    "default-case": "off",
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    "eol-last": "error",
    eqeqeq: "error",
    "for-direction": "error",
    "func-call-spacing": "error",
    "func-name-matching": "error",
    "func-names": "off",
    "func-style": ["error", "declaration", { allowArrowFunctions: true }],
    "function-call-argument-newline": ["error", "consistent"],
    "function-paren-newline": ["error", "multiline-arguments"],
    "generator-star-spacing": ["error", { after: true, before: false }],
    "getter-return": "error",
    "global-require": "error",
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "guard-for-in": "off",
    "handle-callback-err": ["error", "^(.*(([eE][rR][rR])|([eE][rR][rR][oO][rR])))$"],
    "id-blacklist": "off",
    "id-denylist": "off",
    "id-length": ["error", { max: 30, min: 1 }],
    "id-match": "off",
    "implicit-arrow-linebreak": ["error", "beside"],
    indent: ["error", 4, { SwitchCase: 1 }],
    "indent-legacy": "off",
    "init-declarations": "off",
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "line-comment-position": ["error", { ignorePattern: "=>" }],
    "linebreak-style": "error",
    "lines-around-comment": "error",
    "lines-around-directive": "error",
    "lines-between-class-members": "error",
    "logical-assignment-operators": "error",
    "max-classes-per-file": "error",
    "max-depth": ["error", { max: 5 }],
    "max-len": ["error", { code: 135 }],
    "max-lines": ["error", { max: 750, skipBlankLines: true, skipComments: true }],
    "max-lines-per-function": ["error", { max: 150, skipBlankLines: true, skipComments: true }],
    "max-nested-callbacks": ["error", { max: 5 }],
    "max-params": ["error", { max: 5 }],
    "max-statements": ["error", 25],
    "max-statements-per-line": "error",
    "multiline-comment-style": "off",
    "multiline-ternary": ["error", "always-multiline"],
    "new-cap": "error",
    "new-parens": "error",
    "newline-after-var": "error",
    "newline-before-return": "error",
    "newline-per-chained-call": ["error", { ignoreChainWithDepth: 3 }],
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-async-promise-executor": "error",
    "no-await-in-loop": "error",
    "no-bitwise": "off",
    "no-buffer-constructor": "error",
    "no-caller": "error",
    "no-case-declarations": "error",
    "no-catch-shadow": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": ["error", "except-parens"],
    "no-confusing-arrow": "error",
    "no-console": "warn",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-constructor-return": "error",
    "no-continue": "off",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-div-regex": "off",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-duplicate-imports": "error",
    "no-else-return": ["error", { allowElseIf: false }],
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-function": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-label": "error",
    "no-extra-parens": ["error", "all", { enforceForArrowConditionals: false, ignoreJSX: "all", returnAssign: false }],
    "no-extra-semi": "error",
    "no-fallthrough": "off",
    "no-floating-decimal": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-implicit-coercion": ["error", { allow: ["!!"] }],
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-import-assign": "error",
    "no-inline-comments": "off",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-invalid-this": "error",
    "no-irregular-whitespace": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-labels": "off",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-loss-of-precision": "error",
    "no-magic-numbers": "off",
    "no-misleading-character-class": "error",
    "no-mixed-operators": "off",
    "no-mixed-requires": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multi-assign": "error",
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-multiple-empty-lines": ["error", { max: 1 }],
    "no-native-reassign": "error",
    "no-negated-condition": "error",
    "no-negated-in-lhs": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-native-nonconstructor": "error",
    "no-new-object": "error",
    "no-new-require": "error",
    "no-new-symbol": "error",
    "no-new-wrappers": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-object-constructor": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "error",
    "no-path-concat": "error",
    "no-plusplus": "off",
    "no-process-env": "off",
    "no-process-exit": "off",
    "no-promise-executor-return": "error",
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-restricted-exports": "error",
    "no-restricted-globals": "error",
    "no-restricted-imports": "error",
    "no-restricted-modules": "error",
    "no-restricted-properties": "error",
    "no-restricted-syntax": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-script-url": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-setter-return": "error",
    "no-shadow": "error",
    "no-shadow-restricted-names": "error",
    "no-spaced-func": "off",
    "no-sparse-arrays": "error",
    "no-sync": "error",
    "no-tabs": "error",
    "no-template-curly-in-string": "error",
    "no-ternary": "off",
    "no-this-before-super": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-undef": "error",
    "no-undef-init": "error",
    "no-undefined": "off",
    "no-underscore-dangle": "off",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": ["error", { defaultAssignment: false }],
    "no-unreachable": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
    "no-unused-expressions": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
        "error", {
            args: "after-used",
            argsIgnorePattern: "^_",
            caughtErrors: "none",
            caughtErrorsIgnorePattern: "^_",
            destructuredArrayIgnorePattern: "^_",
            ignoreRestSiblings: true,
            vars: "all",
            varsIgnorePattern: "^_",
        },
    ],
    "no-use-before-define": ["error", { functions: false }],
    "no-useless-backreference": "error",
    "no-useless-call": "error",
    "no-useless-catch": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-escape": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-void": ["error", { allowAsStatement: true }],
    "no-warning-comments": "off",
    "no-whitespace-before-property": "error",
    "no-with": "error",
    "nonblock-statement-body-position": ["error", "below"],
    "object-curly-newline": ["error", { multiline: true }],
    "object-curly-spacing": ["error", "always"],
    "object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
    "object-shorthand": "error",
    "one-var": ["error", "never"],
    "one-var-declaration-per-line": "error",
    "operator-assignment": "error",
    "operator-linebreak": "error",
    "padded-blocks": ["error", "never"],
    "padding-line-between-statements": [
        "error", {
            blankLine: "always",
            next: "*",
            prev: "directive",
        }, {
            blankLine: "any",
            next: "directive",
            prev: "directive",
        }, {
            blankLine: "always",
            next: "*",
            prev: "import",
        }, {
            blankLine: "any",
            next: "import",
            prev: "import",
        }, {
            blankLine: "always",
            next: ["class", "if", "while", "switch", "try"],
            prev: "*",
        }, {
            blankLine: "always",
            next: "*",
            prev: ["class", "if", "while", "switch", "try"],
        },
    ],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-named-capture-group": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-reflect": "off",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "quote-props": ["error", "as-needed"],
    quotes: ["error", "double", { allowTemplateLiterals: true, avoidEscape: true }],
    radix: "error",
    "require-atomic-updates": "error",
    "require-await": "error",
    "require-jsdoc": [
        "error", {
            require: {
                ArrowFunctionExpression: false,
                ClassDeclaration: true,
                FunctionDeclaration: true,
                FunctionExpression: false,
                MethodDefinition: true,
            },
        },
    ],
    "require-unicode-regexp": "error",
    "require-yield": "error",
    "rest-spread-spacing": "error",
    semi: "error",
    "semi-spacing": "error",
    "semi-style": "error",
    "sort-imports": "error",
    "sort-keys": "error",
    "sort-vars": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", { anonymous: "always", asyncArrow: "always", named: "never" }],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": ["error", "always", { markers: ["/", "#", "!", "?", "*"] }],
    strict: "error",
    "switch-colon-spacing": "error",
    "symbol-description": "error",
    "template-curly-spacing": "error",
    "template-tag-spacing": "error",
    "unicode-bom": "error",
    "use-isnan": "error",
    "valid-jsdoc": [
        "error", {
            prefer: {
                arg: "param",
                argument: "param",
                constructor: "class",
                return: "returns",
                virtual: "abstract",
            },
            preferType: {
                Boolean: "boolean",
                Number: "number",
                Object: "object",
                String: "string",
            },
            requireParamDescription: true,
            requireParamType: false,
            requireReturn: false,
            requireReturnDescription: true,
            requireReturnType: false,
        },
    ],
    "valid-typeof": "error",
    "vars-on-top": "error",
    "wrap-iife": ["error", "inside"],
    "wrap-regex": "error",
    "yield-star-spacing": "error",
    yoda: "error",
} satisfies EslintRules;
